### ISSUE TITLE
Episode Holiday Special 2015

### ISSUE THREAD

**Issue by vladikoff** [OpenSourceSystemPodcast/projects#34]
Not sure what we can do for the holiday special yet, either it will be just episode 7 or a separate episode: https://github.com/OpenSourceSystemPodcast/projects/issues/33

@shama @miketaylr thoughts?

**Comment by shama** [comment]
I could put some holiday lights around my desk when we record.

**Comment by miketaylr** [comment]
Holiday-themed projects?!??!!? Or projects from only cold countries? (loljk)

**Comment by vladikoff** [comment]
nvm this. :D

**Comment by miketaylr** [comment]
RIP holiday special. :skull:
