### ISSUE TITLE
Episode 9

### ISSUE THREAD

**Issue by miketaylr** [OpenSourceSystemPodcast/projects#36]
https://github.com/superpowers/superpowers

**Comment by vladikoff** [comment]
AWW YESSS

**Comment by vladikoff** [comment]
https://github.com/VerbalExpressions/JSVerbalExpressions

**Comment by vladikoff** [comment]
https://blogs.windows.com/msedgedev/2016/01/13/chakracore-now-open/

**Comment by vladikoff** [comment]
https://patchworksecurity.com/

**Comment by vladikoff** [comment]
https://github.com/loverajoel/jstips

**Comment by vladikoff** [comment]
https://github.com/matryer/bitbar

**Comment by shama** [comment]
https://github.com/google/git-appraise

**Comment by vladikoff** [comment]
http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/

**Comment by vladikoff** [comment]
https://github.com/JakeLin/IBAnimatable

**Comment by vladikoff** [comment]
http://www.openshotvideo.com/2016/01/openshot-20-beta-released.html

**Comment by miketaylr** [comment]
news: https://github.com/nodejs/node/pull/4765

**Comment by shama** [comment]
https://github.com/Jam3/devtool

**Comment by vladikoff** [comment]
https://github.com/superpowers/superpowers TypeScript
https://github.com/google/git-appraise Go
https://github.com/JakeLin/IBAnimatable Swift
https://github.com/Jam3/devtool JS
https://github.com/matryer/bitbar Obj-C
https://github.com/VerbalExpressions/JSVerbalExpressions JS
https://github.com/loverajoel/jstips JS
https://github.com/PaulSec/awesome-sec-talks - Text

News 
- https://blogs.windows.com/msedgedev/2016/01/13/chakracore-now-open/
  - https://github.com/nodejs/node/pull/4765
- http://blog.jquery.com/2016/01/14/jquery-3-0-beta-released/
- http://www.openshotvideo.com/2016/01/openshot-20-beta-released.html

**Comment by vladikoff** [comment]
http://haxe.org/

**Comment by SlexAxton** [comment]
https://egghead.io/series/getting-started-with-redux

**Comment by shama** [comment]
Hacking Elevators: https://www.youtube.com/watch?v=oHf1vD5_b5I

**Comment by SlexAxton** [comment]
changelog: https://github.com/lodash/lodash/wiki/Changelog#v400

https://github.com/lodash/lodash/tree/4.0.0-npm-packages

**Comment by SlexAxton** [comment]
https://www.npmjs.com/browse/depended
